"""Catalog of all UI themes — full QSS themes (not just colour overrides).

Each theme defines a complete QSS string that styles EVERY widget in the app
(cards, buttons, inputs, labels, checkboxes, tabs, scrollbars, popups) using
the theme's colour palette. This is what makes them "real themes" rather than
just backgrounds with recoloured cards.

The 3 preset themes (purple / dark / light) reuse the existing QSS strings
defined in theme.py (DARK_QSS / WIN11_DARK_QSS / WIN11_LIGHT_QSS) — those are
already complete and well-tested.

The 7 image themes are generated by ``_build_image_theme_qss(palette)`` from a
palette dict. The generated QSS has the SAME structure as DARK_QSS (every
selector is covered) but with colours drawn from the palette. This guarantees
no widget is left with the wrong colour.

A theme palette contains:
  - text           — primary text colour (used everywhere a label sits on a card)
  - text_on_accent — text colour on accent-coloured buttons (usually white)
  - text_muted     — secondary/muted text (subtitles, hints)
  - card_bg        — background of every card / glass panel
  - card_border    — border of every card
  - card_hover     — hover background for rows / list items
  - accent         — primary accent (selected nav, focused inputs, primaryBtn)
  - accent_2       — secondary accent (gradient end, scrollbar)
  - nav_glow       — rgba colour for the segmented-nav glow effect
  - is_dark        — whether the theme is overall dark (affects shadow opacity)
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass(frozen=True)
class Theme:
    id: str
    name_ru: str
    name_en: str
    group: str  # "preset" or "image"
    bg_image: Optional[str]  # filename under ui/assets/themes/, or None
    is_dark: bool
    # Palette (used by _build_image_theme_qss for image themes; preset themes
    # ignore these and use their own pre-built QSS).
    text: str = "#ffffff"
    text_on_accent: str = "#ffffff"
    text_muted: str = "rgba(255,255,255,0.65)"
    card_bg: str = "rgba(20, 12, 45, 220)"
    card_border: str = "rgba(255,255,255,0.14)"
    card_hover: str = "rgba(255,255,255,0.10)"
    accent: str = "#7d52ff"
    accent_2: str = "#c44bff"
    nav_glow: str = "rgba(150, 120, 255, 180)"
    # Full QSS — for preset themes this is empty (we use the pre-built strings
    # from theme.py); for image themes it's generated by _build_image_theme_qss.
    qss: str = ""


# ---------------------------------------------------------------------------
# Pre-built QSS strings for the 3 preset themes are imported lazily from
# theme.py to avoid a circular import. We store a sentinel "" and resolve the
# real QSS at apply-time via _preset_qss().
# ---------------------------------------------------------------------------


# --- The 3 existing preset themes (unchanged visual behaviour) ---

_PRESET_PURPLE = Theme(
    id="purple",
    name_ru="Фиолетовая",
    name_en="Purple",
    group="preset",
    bg_image=None,
    is_dark=True,
)

_PRESET_DARK = Theme(
    id="dark",
    name_ru="Тёмная",
    name_en="Dark",
    group="preset",
    bg_image=None,
    is_dark=True,
)

_PRESET_LIGHT = Theme(
    id="light",
    name_ru="Светлая",
    name_en="Light",
    group="preset",
    bg_image=None,
    is_dark=False,
)


# ---------------------------------------------------------------------------
# Image-theme QSS generator. Produces a COMPLETE QSS that covers every widget
# the app uses — same structure as DARK_QSS but with palette colours. This is
# what makes image themes "real themes" rather than just backgrounds.
# ---------------------------------------------------------------------------

def _build_image_theme_qss_from_base(p: dict, base_qss: str) -> str:
    """Build a complete QSS string for an image theme from a base QSS.

    Strategy: take the base QSS (DARK_QSS) verbatim and replace the colour
    values with the theme's palette. This preserves EVERY layout property
    (padding, border-radius, min/max-width, font-size) exactly as the purple
    theme has them — only colours change. This is the only way to keep
    powerBtn at 160x160, navPanel at 18px radius, navBtn at its original
    padding, etc.

    ``base_qss`` is the DARK_QSS string (passed in by the caller to avoid
    importing theme.py at module load time).
    """
    text = p["text"]
    text_on_accent = p["text_on_accent"]
    text_muted = p["text_muted"]
    card_bg = p["card_bg"]
    card_border = p["card_border"]
    card_hover = p["card_hover"]
    accent = p["accent"]
    accent_2 = p["accent_2"]

    qss = base_qss

    # --- Colour substitution table ---
    # Each entry: (substring_in_DARK_QSS, replacement)
    # Order matters: longer/more-specific strings first so we don't partially
    # replace a colour that's a prefix of another.
    replacements = [
        # Primary text colours (the main "#ece8ff" purple-white used everywhere)
        ("#ece8ff", text),
        ("#f4f1ff", text),
        ("#f2eeff", text),
        ("#eee8ff", text),
        ("#ffffff", text_on_accent),
        ("white", text_on_accent),
        # Muted / secondary text
        ("#cfc7ee", text_muted),
        ("#d7cffb", text_muted),
        ("#c7bfe6", text_muted),
        ("#b9b0e0", text_muted),
        ("#9b93c0", text_muted),
        ("#8a82ad", text_muted),
        # Accent purple → theme accent
        ("#7d52ff", accent),
        ("#9d6bff", accent),
        ("#b14bf0", accent),
        ("#be63f5", accent_2),
        ("#8d66ff", accent_2),
        ("#c44bff", accent_2),
        ("#b172ff", accent),
        ("#d0a3ff", accent_2),
        ("#9d3ee0", accent),
        ("#6d42ef", accent_2),
        # Accent gradient stops (qlineargradient with #b14bf0 → #7d52ff)
        # already covered by the individual colour replacements above.
        # Pink/magenta accents (used in navBtn selected, checkbox checked, etc.)
        ("rgba(255, 126, 226, 0.34)", f"rgba({accent[1:3]},{accent[3:5]},{accent[5:7]}, 0.34)"),
        ("rgba(238, 126, 255, 0.96)", f"rgba({accent[1:3]},{accent[3:5]},{accent[5:7]}, 0.96)"),
        ("rgba(255, 180, 255, 0.95)", f"rgba({accent[1:3]},{accent[3:5]},{accent[5:7]}, 0.95)"),
        ("rgba(255,220,255,1.0)", f"rgba({accent[1:3]},{accent[3:5]},{accent[5:7]}, 1.0)"),
        ("rgba(255, 185, 255, 0.94)", f"rgba({accent[1:3]},{accent[3:5]},{accent[5:7]}, 0.94)"),
        ("rgba(255,185,255,0.90)", f"rgba({accent[1:3]},{accent[3:5]},{accent[5:7]}, 0.90)"),
        ("rgba(255,185,255,0.94)", f"rgba({accent[1:3]},{accent[3:5]},{accent[5:7]}, 0.94)"),
        # Card backgrounds (the translucent dark-purple fills)
        ("rgba(16, 8, 56, 0.42)", card_bg),
        ("rgba(16, 8, 56, 0.50)", card_bg),
        ("rgba(18,12,38,0.34)", card_bg),
        ("rgba(34, 16, 92, 0.30)", card_bg),
        ("rgba(14, 7, 48, 0.48)", card_bg),
        ("rgba(12,10,36,0.55)", card_bg),
        ("rgba(12, 4, 44, 0.54)", card_bg),
        ("rgba(18, 6, 58, 0.70)", card_bg),
        ("#1c1640", card_bg if not card_bg.startswith("rgba") else card_bg),
        ("#211a44", card_bg if not card_bg.startswith("rgba") else card_bg),
        ("#0c0a24", card_bg if not card_bg.startswith("rgba") else card_bg),
        # Borders
        ("rgba(255,255,255,0.14)", card_border),
        ("rgba(255,255,255,0.10)", card_border),
        ("rgba(255,255,255,0.08)", card_border),
        ("rgba(255,255,255,0.12)", card_border),
        ("rgba(255,255,255,0.18)", card_border),
        ("rgba(255,255,255,0.20)", card_border),
        ("rgba(255,255,255,0.24)", card_border),
        ("rgba(255,255,255,0.40)", card_border),
        ("rgba(255,255,255,0.34)", card_border),
        ("rgba(255,255,255,0.38)", card_border),
        ("rgba(255,255,255,0.42)", card_border),
        ("rgba(255,255,255,0.46)", card_border),
        ("rgba(255,255,255,0.76)", card_border),
        ("rgba(255,255,255,0.84)", card_border),
        ("rgba(255,255,255,0.92)", card_border),
        ("rgba(255,255,255,0.95)", card_border),
        ("rgba(255,210,255,0.76)", card_border),
        # Hover backgrounds
        ("rgba(255,255,255,0.10)", card_hover),
        ("rgba(255,255,255,0.12)", card_hover),
        ("rgba(255,255,255,0.16)", card_hover),
        ("rgba(255,255,255,0.18)", card_hover),
        ("rgba(255,255,255,0.20)", card_hover),
        ("rgba(255,255,255,0.24)", card_hover),
        ("rgba(255,255,255,0.26)", card_hover),
        ("rgba(255,255,255,0.28)", card_hover),
        ("rgba(255,255,255,0.30)", card_hover),
        ("rgba(255,255,255,0.31)", card_hover),
        ("rgba(255,255,255,0.42)", card_hover),
        ("rgba(255,255,255,0.60)", card_hover),
        ("rgba(255,255,255,0.50)", card_hover),
        ("rgba(255,255,255,0.54)", card_hover),
        # Light translucent fills (glassCard, runBox, etc.)
        ("rgba(255,255,255,0.05)", card_hover),
        ("rgba(255,255,255,0.06)", card_hover),
        ("rgba(255,255,255,0.07)", card_hover),
        ("rgba(255,255,255,0.08)", card_hover),
        ("rgba(255,255,255,0.04)", card_hover),
        ("rgba(255,255,255,0.13)", card_hover),
        ("rgba(255,255,255,0.14)", card_hover),
        ("rgba(255,255,255,0.15)", card_hover),
        # Settings card specific colours
        ("rgba(104, 185, 216, 0.78)", accent),
        ("rgba(123, 205, 232, 0.90)", accent_2),
        ("rgba(94, 175, 210, 0.86)", accent),
        ("rgba(225,245,255,0.98)", card_border),
        # Ghost button (red-ish)
        ("rgba(255,90,108,0.16)", "rgba(224, 69, 90, 0.16)"),
        ("rgba(255,90,108,0.26)", "rgba(224, 69, 90, 0.26)"),
        ("rgba(255,90,108,0.45)", "rgba(224, 69, 90, 0.45)"),
        ("#ffb3bc", "rgba(224, 69, 90, 0.9)"),
        # Power button running state (green when running)
        ("#8af0b0", "#37c871" if p.get("is_dark") else "#2a9d54"),
        ("rgba(120,240,170,0.55)", "rgba(55, 200, 113, 0.55)"),
        ("rgba(80,220,140,0.10)", "rgba(55, 200, 113, 0.10)"),
        # Scrollbar
        # Already handled by accent replacements above.
    ]

    for old, new in replacements:
        qss = qss.replace(old, new)

    return qss


# --- 7 image themes, each with a hand-tuned palette ---

def _image_theme(
    id: str, name_ru: str, name_en: str, bg_image: str, is_dark: bool,
    text: str, text_muted: str, text_on_accent: str,
    card_bg: str, card_border: str, card_hover: str,
    accent: str, accent_2: str, nav_glow: str,
) -> Theme:
    """Build an image Theme. The QSS is generated lazily in get_theme_qss()
    from DARK_QSS + colour substitution, so we don't need PyQt6 at module
    load time."""
    return Theme(
        id=id,
        name_ru=name_ru,
        name_en=name_en,
        group="image",
        bg_image=bg_image,
        is_dark=is_dark,
        text=text,
        text_muted=text_muted,
        text_on_accent=text_on_accent,
        card_bg=card_bg,
        card_border=card_border,
        card_hover=card_hover,
        accent=accent,
        accent_2=accent_2,
        nav_glow=nav_glow,
        qss="",  # Generated lazily in get_theme_qss()
    )


_IMAGE_MIST = _image_theme(
    id="mist", name_ru="Туман", name_en="Mist", bg_image="bg_mist.jpg", is_dark=True,
    text="#eef2f6", text_muted="rgba(238,242,246,0.66)", text_on_accent="#ffffff",
    card_bg="rgba(18, 24, 32, 0.52)", card_border="rgba(255,255,255,0.16)",
    card_hover="rgba(255,255,255,0.10)",
    accent="#5b8cb8", accent_2="#7fb0d4", nav_glow="rgba(120, 170, 215, 180)",
)

_IMAGE_AZURE = _image_theme(
    id="azure", name_ru="Лазурь", name_en="Azure", bg_image="bg_azure.jpg", is_dark=True,
    text="#eaf4ff", text_muted="rgba(234,244,255,0.66)", text_on_accent="#ffffff",
    card_bg="rgba(10, 26, 46, 0.54)", card_border="rgba(255,255,255,0.16)",
    card_hover="rgba(255,255,255,0.10)",
    accent="#2f7fd0", accent_2="#4fb0e8", nav_glow="rgba(90, 170, 235, 180)",
)

_IMAGE_SNOW = _image_theme(
    id="snow", name_ru="Снег", name_en="Snow", bg_image="bg_snow.jpg", is_dark=False,
    text="#1b2230", text_muted="rgba(27,34,48,0.62)", text_on_accent="#ffffff",
    card_bg="rgba(255, 255, 255, 0.72)", card_border="rgba(20,30,50,0.14)",
    card_hover="rgba(20,30,50,0.07)",
    accent="#4a7bc8", accent_2="#79a5e0", nav_glow="rgba(120, 165, 225, 150)",
)

_IMAGE_LAVENDER = _image_theme(
    id="lavender", name_ru="Лаванда", name_en="Lavender", bg_image="bg_lavender.jpg", is_dark=True,
    text="#f2ecff", text_muted="rgba(242,236,255,0.66)", text_on_accent="#ffffff",
    card_bg="rgba(28, 18, 48, 0.54)", card_border="rgba(255,255,255,0.16)",
    card_hover="rgba(255,255,255,0.10)",
    accent="#8a63d2", accent_2="#b48ae8", nav_glow="rgba(165, 130, 235, 180)",
)

_IMAGE_FOG = _image_theme(
    id="fog", name_ru="Дымка", name_en="Fog", bg_image="bg_fog.jpg", is_dark=True,
    text="#eceff2", text_muted="rgba(236,239,242,0.64)", text_on_accent="#ffffff",
    card_bg="rgba(24, 26, 30, 0.56)", card_border="rgba(255,255,255,0.15)",
    card_hover="rgba(255,255,255,0.09)",
    accent="#6b7280", accent_2="#9aa3ae", nav_glow="rgba(160, 170, 185, 170)",
)

_IMAGE_SAND = _image_theme(
    id="sand", name_ru="Песок", name_en="Sand", bg_image="bg_sand.jpg", is_dark=False,
    text="#2a2318", text_muted="rgba(42,35,24,0.62)", text_on_accent="#ffffff",
    card_bg="rgba(255, 250, 240, 0.72)", card_border="rgba(60,45,25,0.14)",
    card_hover="rgba(60,45,25,0.07)",
    accent="#b8894a", accent_2="#d9ae72", nav_glow="rgba(215, 175, 120, 160)",
)

_IMAGE_MIDNIGHT = _image_theme(
    id="midnight", name_ru="Полночь", name_en="Midnight", bg_image="bg_midnight.jpg", is_dark=True,
    text="#e8ecf6", text_muted="rgba(232,236,246,0.64)", text_on_accent="#ffffff",
    card_bg="rgba(8, 10, 22, 0.62)", card_border="rgba(255,255,255,0.14)",
    card_hover="rgba(255,255,255,0.09)",
    accent="#3d4fa8", accent_2="#6373d4", nav_glow="rgba(100, 120, 220, 175)",
)


# The catalog order is the order themes appear in the dropdown.
THEMES: List[Theme] = [
    _PRESET_PURPLE,
    _PRESET_DARK,
    _PRESET_LIGHT,
    _IMAGE_MIST,
    _IMAGE_AZURE,
    _IMAGE_SNOW,
    _IMAGE_LAVENDER,
    _IMAGE_FOG,
    _IMAGE_SAND,
    _IMAGE_MIDNIGHT,
]


def get_theme(theme_id: str) -> Theme:
    """Return the Theme with the given id, falling back to 'purple'."""
    for t in THEMES:
        if t.id == theme_id:
            return t
    return _PRESET_PURPLE


def theme_ids() -> List[str]:
    return [t.id for t in THEMES]


def is_image_theme(theme_id: str) -> bool:
    """True if the theme uses a photographic background (vs procedural)."""
    t = get_theme(theme_id)
    return t.group == "image" and t.bg_image is not None


def get_theme_qss(theme_id: str, base_qss: dict) -> str:
    """Return the FULL QSS string to apply for the given theme.

    ``base_qss`` is a dict with keys "DARK", "WIN11_DARK", "WIN11_LIGHT"
    pointing at the pre-built QSS strings from theme.py. Preset themes use
    these directly; image themes generate their QSS lazily from DARK_QSS +
    colour substitution (so the layout properties are preserved exactly).
    """
    t = get_theme(theme_id)
    if t.group == "image":
        # If the theme already has a pre-built QSS (from module load time),
        # use it. Otherwise generate it now from the DARK_QSS passed in
        # base_qss. This lazy generation avoids requiring PyQt6 at import
        # time (needed for unit tests).
        if t.qss:
            return t.qss
        # Generate from DARK_QSS + palette.
        palette = {
            "text": t.text,
            "text_on_accent": t.text_on_accent,
            "text_muted": t.text_muted,
            "card_bg": t.card_bg,
            "card_border": t.card_border,
            "card_hover": t.card_hover,
            "accent": t.accent,
            "accent_2": t.accent_2,
            "nav_glow": t.nav_glow,
            "is_dark": t.is_dark,
        }
        return _build_image_theme_qss_from_base(palette, base_qss["DARK"])
    # Preset themes use the pre-built strings from theme.py.
    if t.id == "dark":
        return base_qss["WIN11_DARK"]
    if t.id == "light":
        return base_qss["WIN11_LIGHT"]
    return base_qss["DARK"]
